- name: Playbook to configure ansible connection to dynamic hosts
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Adding provided host
      ansible.builtin.add_host:
        name: "{{ dynamic_host }}"

- name: Print hostname
  hosts: "all:!localhost"
  gather_facts: true

  tasks:
    - name: Print hostname
      ansible.builtin.debug:
        msg: "{{ ansible_hostname }}"
